include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  exclude:
    - build/**
    - .dart_tool/**
    - ios/**
    - android/**

linter:
  rules:
    # Consistency and readability
    prefer_single_quotes: true
    require_trailing_commas: true
    directives_ordering: true
    sort_constructors_first: true
    always_declare_return_types: true
    type_annotate_public_apis: true

    # Performance and immutability
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true
    unnecessary_late: true

    # API ergonomics
    use_super_parameters: true
    unawaited_futures: true
    avoid_print: true
